export const ALARM_SERVICE = 'ALARM_SERVICE';
export const ALARM_SERVICE_NEW = 'ALARM_SERVICE_NEW'
export const ALARM_TOPIC_SERVICE = 'ALARM_TOPIC_SERVICE'
export const ALARM_FANOUT_SERVICE = 'ALARM_FANOUT_SERVICE'
export const ALARM_HEADERS_SERVICE = 'ALARM_HEADERS_SERVICE'